version: "3.9"
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_workflowhr
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - postgres-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "auth_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge

volumes:
  postgres_data: